### ISSUE TITLE
python变量命名空间LEGB | 易金经

### ISSUE THREAD

**Issue by goodcode-200** [xikebyme/Mysite_gitTalk#24]
https://www.66xk.wang/2019/09/13/python%E5%8F%98%E9%87%8F%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4LEGB/ 

 文档 A namespace is a mapping from names to objects.  Most namespaces are currently implemented as Python dictionaries, but that’s normally not noticeable in any way (except for performance), and it may

**Comment by goodcode-200** [comment]
LEGB

**Comment by xikebyme** [comment]
66xk.wang的登录转到www.66xk.wang
